server:
  port: 9091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/LibraryDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

